name: Deploy front

on:
  push:
    branches: [main, devops]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Set up environment variables
      run: |
        echo "${{ secrets.ENV }}" >> .env

    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy with compose
      run: |
        docker compose up -d --build